# Generated by Django 4.2 on 2023-10-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_testimony_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureExcerpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(blank=True, help_text='short informations about the image. NOTE: this field can be ignored', max_length=100)),
            ],
            options={
                'verbose_name': 'Picture Excerpt',
                'verbose_name_plural': 'Picture Excerpts',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='specialization',
            field=models.CharField(max_length=50),
        ),
    ]
